# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PLPlayerDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PLPlayerDemo

pod "PLPlayerKit", :podspec => 'https://raw.githubusercontent.com/pili-engineering/PLPlayerKit/master/PLPlayerKit-Universal.podspec'
pod 'SnapKit'
pod 'JGProgressHUD'

end
